name: Debug with tmate

on:
  workflow_dispatch:
    inputs:
      runs-on:
        type: choice
        description: 'Select runner platform'
        required: true
        default: ubuntu-latest
        options:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - macos-15
          - macos-14
          - macos-13
          - windows-2025
          - windows-2022
          - windows-11-arm


jobs:
  debug:
    name: Debug Session
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3


